version: '3'
services:
  rabbit:
    image: rabbitmq:alpine
  redis:
    image: redis:alpine
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: kra3/scraper
    ports:
      - 8080
    depends_on:
      - "rabbit"
      - "redis"