version: '3'
services:
  rabbit:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080
    depends_on:
      - "rabbit"
      - "redis"